export const data=[
    {
        id:1,
        img:"https://i.ibb.co/z50GfTd/Weather.jpg",
        link:"https://brusque-dispatcher.000webhostapp.com/"
    },
    {
        id:2,
        img:"https://i.ibb.co/SNfs6NH/Tindog.jpg",
        link:"https://nikhilmourya.github.io/Tindog/"
    },
    {
        id:3,
        img:"https://i.ibb.co/wcTf0f5/Digichef-Clone.jpg",
        link:"https://nikhilmourya.github.io/DigichefClone/"
    },
    {
        id:4,
        img:"https://i.ibb.co/MpL26hZ/Talent-Ease.jpg",
        link:"https://nikhilmourya.github.io/TalentEase/"
    },
];
